### PR TITLE
Store the specification in the repository itself

### PR DESCRIPTION
**Pull request by Lexicality**
Currently the only way to find the spec after googing "gmod CAMI" is to open the source file and find the gdoc link.

This PR moves the spec (slightly reformatted) into `README.md` so it'll be immediately obvious on landing in the repo.

### CODE REVIEW

**Comment by Lexicality** [comment]
(I feel like the "How to integrate with CAMI" sections should be entire files and be way more detailed, but I cba to do that)

**Comment by FPtje** [comment]
Problem is, it'll become harder to merge this repo into other repos. I would have added README and LICENSE files if it wasn't for git read-tree breaking. This is what I use to merge CAMI (and other libraries) into DarkRP:

```bash
git fetch CAMI &&
git rm gamemode/libraries/sh_cami.lua &&
git read-tree --prefix=gamemode/libraries/ -u CAMI/master &&
git commit -m "Merged CAMI"
```  

Now there is a way to specify which subdirectories to merge, as I do with FPP:
```bash
git fetch FPP &&
git rm gamemode/modules/fpp/pp/* -r &&
git read-tree --prefix=gamemode/modules/fpp/pp -u FPP/master:lua/fpp &&
git commit -m "Merged FPP"
```
But that doesn't work with single files (`sh_cami.lua`)

I could make a different script that doesn't use git read-tree, but I'm not sure if other people are using similar methods to update CAMI.

**Comment by Lexicality** [comment]
To be honest, I didn't expect anyone to be using a script for this.
It's a single file that updates every 4 years, so I figured people would just copy/paste it.

**Comment by Lexicality** [comment]
I guess one solution would be to turn this repo into a valid addon by moving `sh_cami.lua` to `lua/autorun/sh_cami.lua`.
That way `git read-tree` will be possible again, and the option for people to do other weird things (like installing it on their server) is opened up.

**Comment by FPtje** [comment]
That would be a good idea yeah. Could you do that in this PR?

**Pull request merged**
