### PR TITLE
Changing indentation and cleanup

### PR DESCRIPTION
**Pull request by FlorianLeChat**
+ Deleting a useless space.
+ Tabs to spaces.

(Same pull request [here](https://github.com/FPtje/DarkRP/pull/2803))

### CODE REVIEW

**Comment by Kefta** [comment]
It's slower to use player.GetCount over counting the table when you already have it. Speed isn't really the concern here, but either way, best not to change it.

**Comment by FlorianLeChat** [comment]
I agree with you. I remove this change.

**Comment by gspetrou** [comment]
Tabs to spaces? I too enjoy hitting the left arrow key 4 times instead of just once.

**Comment by FPtje** [comment]
I'll accept it, but could you please use other commit names than "updated <file>?"

**Comment by FlorianLeChat** [comment]
Done if it's good for you.

**Comment by FPtje** [comment]
It's good. Thanks.

**Comment by SwadicalRag** [comment]
good luck with your hacktober t shirt

if you dont get one im sure @LennyPenny will give u one from his collection

**Comment by LennyPenny** [comment]
😊

**Pull request merged**
